version: '2'
services:
  postgres:
    image: postgres:10
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    ports:
      - "9999:5432"
    environment:
      - POSTGRES_USER=training
      - POSTGRES_PASSWORD=training
      - POSTGRES_DB=training
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data